import fs from 'node:fs';
import path from 'node:path';

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

export type DocsDomainDefinition = {
  key: string;
  dirName: string;
  sidebarId: string;
  label: string;
  position: number;
  docId?: string;
  description?: string;
  showLandingInSidebar?: boolean;
  ownedRoots: string[];
  ownedDocs: string[];
  catchAll?: boolean;
};

export type GeneralDocsDefinition = {
  sidebarId: string;
  label: string;
  docIds: string[];
};

export type DocsDomainCatalog = {
  domains: DocsDomainDefinition[];
  generalDocs: GeneralDocsDefinition | null;
};

type RawDomainConfig = {
  schemaVersion?: number;
  domains?: Array<{
    key?: string;
    dirName?: string;
    sidebarId?: string;
    label?: string;
    position?: number;
    landingDoc?: string;
    description?: string;
    showLandingInSidebar?: boolean;
    ownedRoots?: string[];
    ownedDocs?: string[];
    catchAll?: boolean;
  }>;
};

type SidebarAutogeneratedItem = {
  type: 'autogenerated';
  dirName: string;
};

type SidebarCategoryItem = {
  type: 'category';
  label: string;
  items: SidebarItem[];
  link?: {
    type: 'doc';
    id: string;
  };
};

type SidebarItem = string | SidebarAutogeneratedItem | SidebarCategoryItem;

const DOCS_ROOT = path.resolve(__dirname, '../Docs');
const DOMAINS_CONFIG_PATH = path.join(DOCS_ROOT, '_domains.json');
const MARKDOWN_EXTENSIONS = new Set(['.md', '.mdx']);
const STANDARD_DIR_NAMES = new Set([
  'workflowstandards',
  'workflow',
  'codingstandards',
  'docssite',
  'ai',
  'aicontext',
  'testing',
  'pipeline',
  'setup',
  'gitstandards',
  'unrealstandards',
]);
const STANDARD_DOC_IDS = new Set(['setup', 'testing']);

function isMarkdownFile(fileName: string): boolean {
  return MARKDOWN_EXTENSIONS.has(path.extname(fileName).toLowerCase());
}

function isVisibleDirectory(entryName: string): boolean {
  return !!entryName && !entryName.startsWith('.');
}

function normalizeToken(value: string): string {
  return value.replace(/\\/g, '/').replace(/^\/+|\/+$/g, '').trim();
}

function stripNumberPrefix(segment: string): string {
  return segment.replace(/^\d+[-_](?=[A-Za-z])/, '');
}

function normalizeDocsPathSegments(relativePath: string): string {
  return relativePath
    .split('/')
    .map((segment) => stripNumberPrefix(segment))
    .join('/');
}

function isExcludedDocsPath(fullPath: string): boolean {
  const relativePath = normalizeToken(path.relative(DOCS_ROOT, fullPath));
  if (!relativePath) {
    return false;
  }

  const segments = relativePath.split('/');
  if (segments.some((segment) => /^(Current|Templates)$/i.test(segment))) {
    return true;
  }

  const fileName = segments[segments.length - 1] ?? '';
  return /\.template\.(md|mdx)$/i.test(fileName);
}

function toDocId(fullPath: string): string {
  const relativePath = path.relative(DOCS_ROOT, fullPath).replace(/\\/g, '/');
  return normalizeDocsPathSegments(relativePath).replace(/\.(md|mdx)$/i, '');
}

function toSidebarId(value: string): string {
  const slug = normalizeToken(value)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^A-Za-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
  return slug ? `${slug}-sidebar` : 'docs-sidebar';
}

function toDisplayLabel(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/[-_]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function readJsonFile(filePath: string): Record<string, unknown> | null {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8')) as Record<string, unknown>;
  } catch {
    return null;
  }
}

function readDomainsConfig(): RawDomainConfig | null {
  if (!fs.existsSync(DOMAINS_CONFIG_PATH)) {
    return null;
  }
  try {
    return JSON.parse(fs.readFileSync(DOMAINS_CONFIG_PATH, 'utf8')) as RawDomainConfig;
  } catch {
    return null;
  }
}

function readTextFile(filePath: string): string {
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch {
    return '';
  }
}

function extractFrontMatterValue(content: string, key: string): string {
  const frontMatterMatch = content.match(/^---\s*\r?\n([\s\S]*?)\r?\n---\s*/);
  if (!frontMatterMatch) {
    return '';
  }
  const pattern = new RegExp(`^\\s*${key}\\s*:\\s*(.+?)\\s*$`, 'm');
  const frontMatterBody = frontMatterMatch[1] ?? '';
  const match = frontMatterBody.match(pattern);
  return match ? match[1].trim().replace(/^['"]|['"]$/g, '') : '';
}

function extractHeading(content: string): string {
  const match = content.match(/^\#\s+(.+?)\s*$/m);
  return match ? match[1].trim() : '';
}

function getDirectoryReadmePath(directoryPath: string): string | null {
  const candidates = new Set(['readme.md', 'readme.mdx', 'index.md', 'index.mdx']);
  for (const entry of fs.readdirSync(directoryPath, {withFileTypes: true})) {
    if (!entry.isFile()) {
      continue;
    }
    if (candidates.has(entry.name.toLowerCase())) {
      return path.join(directoryPath, entry.name);
    }
  }
  return null;
}

function getDirectoryLabel(directoryPath: string, fallbackName: string): string {
  const categoryJson = readJsonFile(path.join(directoryPath, '_category_.json'));
  const categoryLabel = typeof categoryJson?.label === 'string' ? categoryJson.label.trim() : '';
  if (categoryLabel) {
    return categoryLabel;
  }

  const readmePath = getDirectoryReadmePath(directoryPath);
  if (readmePath) {
    const content = readTextFile(readmePath);
    const title = extractFrontMatterValue(content, 'title') || extractHeading(content);
    if (title) {
      return title;
    }
  }

  return toDisplayLabel(fallbackName);
}

function getDirectoryDescription(directoryPath: string): string {
  const readmePath = getDirectoryReadmePath(directoryPath);
  if (!readmePath) {
    return '';
  }
  const content = readTextFile(readmePath);
  return extractFrontMatterValue(content, 'description');
}

function getDirectoryPosition(directoryPath: string): number {
  const categoryJson = readJsonFile(path.join(directoryPath, '_category_.json'));
  const rawPosition = categoryJson?.position;
  if (typeof rawPosition === 'number' && Number.isFinite(rawPosition)) {
    return rawPosition;
  }
  if (typeof rawPosition === 'string') {
    const parsed = Number.parseFloat(rawPosition);
    if (Number.isFinite(parsed)) {
      return parsed;
    }
  }
  return Number.POSITIVE_INFINITY;
}

function getDocPosition(filePath: string): number {
  const content = readTextFile(filePath);
  const rawPosition = extractFrontMatterValue(content, 'sidebar_position');
  if (!rawPosition) {
    return Number.POSITIVE_INFINITY;
  }

  const parsed = Number.parseFloat(rawPosition);
  return Number.isFinite(parsed) ? parsed : Number.POSITIVE_INFINITY;
}

function getDirectoryLandingDocId(directoryPath: string): string | null {
  const categoryJson = readJsonFile(path.join(directoryPath, '_category_.json'));
  const link = categoryJson?.link;
  if (link && typeof link === 'object') {
    const linkType = Reflect.get(link, 'type');
    const linkId = Reflect.get(link, 'id');
    if (linkType === 'doc' && typeof linkId === 'string' && linkId.trim()) {
      const normalizedId = normalizeToken(linkId);
      if (!normalizedId) {
        return null;
      }

      const directoryDocPrefix = normalizeToken(path.relative(DOCS_ROOT, directoryPath));
      if (!directoryDocPrefix) {
        return normalizedId;
      }

      if (normalizedId.includes('/')) {
        return normalizedId;
      }

      return `${directoryDocPrefix}/${normalizedId}`;
    }
  }

  const readmePath = getDirectoryReadmePath(directoryPath);
  return readmePath ? toDocId(readmePath) : null;
}

function buildDirectoryChildSidebarItems(directoryPath: string): SidebarItem[] {
  const entries = fs.readdirSync(directoryPath, {withFileTypes: true});
  const items = entries
    .filter((entry) => {
      if (entry.isDirectory()) {
        const fullPath = path.join(directoryPath, entry.name);
        return (
          isVisibleDirectory(entry.name) &&
          !isExcludedDocsPath(fullPath) &&
          directoryHasDocsContent(fullPath)
        );
      }
      if (entry.isFile()) {
        const fullPath = path.join(directoryPath, entry.name);
        return (
          !isExcludedDocsPath(fullPath) &&
          isMarkdownFile(entry.name) &&
          !/^readme\.(md|mdx)$/i.test(entry.name) &&
          !/^index\.(md|mdx)$/i.test(entry.name)
        );
      }
      return false;
    })
    .map((entry) => {
      const fullPath = path.join(directoryPath, entry.name);
      if (entry.isDirectory()) {
        const categoryItem: SidebarCategoryItem = {
          type: 'category',
          label: getDirectoryLabel(fullPath, entry.name),
          items: buildDirectoryChildSidebarItems(fullPath),
        };
        const landingDocId = getDirectoryLandingDocId(fullPath);
        if (landingDocId) {
          categoryItem.link = {
            type: 'doc',
            id: landingDocId,
          };
        }
        return {
          item: categoryItem,
          position: getDirectoryPosition(fullPath),
          label: categoryItem.label,
        };
      }

      return {
        item: toDocId(fullPath) as SidebarItem,
        position: getDocPosition(fullPath),
        label: entry.name,
      };
    });

  items.sort((left, right) => {
    if (left.position !== right.position) {
      return left.position - right.position;
    }
    return left.label.localeCompare(right.label);
  });

  return items.map((entry) => entry.item);
}

function directoryHasDocsContent(directoryPath: string): boolean {
  const entries = fs.readdirSync(directoryPath, {withFileTypes: true});
  for (const entry of entries) {
    const fullPath = path.join(directoryPath, entry.name);
    if (isExcludedDocsPath(fullPath)) {
      continue;
    }
    if (entry.isFile() && isMarkdownFile(entry.name)) {
      return true;
    }
    if (entry.isDirectory() && isVisibleDirectory(entry.name) && directoryHasDocsContent(fullPath)) {
      return true;
    }
  }
  return false;
}

function getTopLevelDirectoryNames(): string[] {
  if (!fs.existsSync(DOCS_ROOT)) {
    return [];
  }
  return fs
    .readdirSync(DOCS_ROOT, {withFileTypes: true})
    .filter((entry) => entry.isDirectory() && isVisibleDirectory(entry.name) && directoryHasDocsContent(path.join(DOCS_ROOT, entry.name)))
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right));
}

function getTopLevelMarkdownDocIds(): string[] {
  if (!fs.existsSync(DOCS_ROOT)) {
    return [];
  }
  return fs
    .readdirSync(DOCS_ROOT, {withFileTypes: true})
    .filter((entry) => entry.isFile() && isMarkdownFile(entry.name) && !/^readme\.(md|mdx)$/i.test(entry.name))
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((entry) => toDocId(path.join(DOCS_ROOT, entry.name)));
}

function findDocPathFromDocId(docId: string): string | null {
  const normalized = normalizeToken(docId);
  if (!normalized) {
    return null;
  }

  for (const extension of MARKDOWN_EXTENSIONS) {
    const fullPath = path.join(DOCS_ROOT, `${normalized}${extension}`);
    if (fs.existsSync(fullPath) && fs.statSync(fullPath).isFile()) {
      return fullPath;
    }
  }

  return null;
}

function buildDefaultDomainConfig(topLevelDirectories: string[], topLevelDocIds: string[]): DocsDomainDefinition[] {
  const standardRoots = topLevelDirectories.filter((entry) => STANDARD_DIR_NAMES.has(entry.toLowerCase()));
  const projectRoots = topLevelDirectories.filter((entry) => !STANDARD_DIR_NAMES.has(entry.toLowerCase()));
  const standardDocs = topLevelDocIds.filter((entry) => STANDARD_DOC_IDS.has(entry.toLowerCase()));
  const projectDocs = topLevelDocIds.filter((entry) => !STANDARD_DOC_IDS.has(entry.toLowerCase()));

  return [
    {
      key: 'workflow-standards',
      dirName: 'WorkflowStandards',
      sidebarId: 'workflow-standards-sidebar',
      label: 'Workflow & Standards',
      position: 10,
      docId: 'WorkflowStandards/README',
      description: 'Best practices, setup guidance, and technical standards for the project.',
      showLandingInSidebar: false,
      ownedRoots: Array.from(new Set(['WorkflowStandards', ...standardRoots])),
      ownedDocs: standardDocs,
      catchAll: false,
    },
    {
      key: 'project-docs',
      dirName: 'ProjectDocs',
      sidebarId: 'project-docs-sidebar',
      label: 'Project Docs',
      position: 20,
      docId: 'ProjectDocs/README',
      description: 'Project-specific design, gameplay, and implementation documentation.',
      showLandingInSidebar: false,
      ownedRoots: Array.from(new Set(['ProjectDocs', ...projectRoots])),
      ownedDocs: projectDocs,
      catchAll: projectRoots.length === 0 && projectDocs.length === 0,
    },
  ];
}

function normalizeConfigDomains(rawConfig: RawDomainConfig | null, topLevelDirectories: string[], topLevelDocIds: string[]): DocsDomainDefinition[] {
  const configuredDomains = rawConfig?.domains ?? [];
  if (configuredDomains.length === 0) {
    return buildDefaultDomainConfig(topLevelDirectories, topLevelDocIds);
  }

  const claimedRoots = new Set<string>();
  const claimedDocs = new Set<string>();
  const domains: DocsDomainDefinition[] = configuredDomains.map((entry, index) => {
    const key = normalizeToken(entry.key || entry.dirName || `domain-${index + 1}`) || `domain-${index + 1}`;
    const dirName = normalizeToken(entry.dirName || key) || key;
    const landingDoc = normalizeToken(typeof entry.landingDoc === 'string' ? entry.landingDoc : '');
    const sidebarId = normalizeToken(entry.sidebarId || toSidebarId(key)) || toSidebarId(key);
    const label = (entry.label || toDisplayLabel(dirName)).trim();
    const ownedRoots = Array.from(
      new Set((entry.ownedRoots ?? []).map((value) => normalizeToken(value)).filter(Boolean)),
    ).filter((value) => {
      const exists = topLevelDirectories.includes(value);
      if (exists) {
        claimedRoots.add(value);
      }
      return exists;
    });
    const ownedDocs = Array.from(
      new Set((entry.ownedDocs ?? []).map((value) => normalizeToken(value)).filter(Boolean)),
    ).filter((value) => {
      const exists = topLevelDocIds.includes(value);
      if (exists) {
        claimedDocs.add(value);
      }
      return exists;
    });

    return {
      key,
      dirName,
      sidebarId,
      label,
      position: typeof entry.position === 'number' && Number.isFinite(entry.position) ? entry.position : (index + 1) * 10,
      docId: landingDoc || undefined,
      description: entry.description?.trim() || undefined,
      showLandingInSidebar: entry.showLandingInSidebar === true,
      ownedRoots,
      ownedDocs,
      catchAll: entry.catchAll === true,
    };
  });

  const workflowDomain = domains.find(
    (domain) => domain.key === 'workflow-standards' || domain.dirName === 'WorkflowStandards',
  );
  if (workflowDomain) {
    for (const directoryName of topLevelDirectories) {
      if (
        STANDARD_DIR_NAMES.has(directoryName.toLowerCase()) &&
        !claimedRoots.has(directoryName) &&
        !workflowDomain.ownedRoots.includes(directoryName)
      ) {
        workflowDomain.ownedRoots.push(directoryName);
        claimedRoots.add(directoryName);
      }
    }
    for (const docId of topLevelDocIds) {
      if (STANDARD_DOC_IDS.has(docId.toLowerCase()) && !claimedDocs.has(docId) && !workflowDomain.ownedDocs.includes(docId)) {
        workflowDomain.ownedDocs.push(docId);
        claimedDocs.add(docId);
      }
    }
  }

  const catchAllDomain = domains.find((domain) => domain.catchAll);
  if (catchAllDomain) {
    for (const directoryName of topLevelDirectories) {
      if (!claimedRoots.has(directoryName) && !catchAllDomain.ownedRoots.includes(directoryName)) {
        catchAllDomain.ownedRoots.push(directoryName);
      }
    }
    for (const docId of topLevelDocIds) {
      if (!claimedDocs.has(docId) && !catchAllDomain.ownedDocs.includes(docId)) {
        catchAllDomain.ownedDocs.push(docId);
      }
    }
  }

  return domains.sort((left, right) => {
    if (left.position !== right.position) {
      return left.position - right.position;
    }
    return left.label.localeCompare(right.label);
  });
}

export function getDocsDomainCatalog(): DocsDomainCatalog {
  if (!fs.existsSync(DOCS_ROOT)) {
    return {domains: [], generalDocs: null};
  }

  const topLevelDirectories = getTopLevelDirectoryNames();
  const topLevelDocIds = getTopLevelMarkdownDocIds();
  const rawConfig = readDomainsConfig();
  const domains = normalizeConfigDomains(rawConfig, topLevelDirectories, topLevelDocIds);

  const enrichedDomains = domains.map((domain) => {
    const domainDirectoryPath = path.join(DOCS_ROOT, domain.dirName);
    const fallbackLabel = fs.existsSync(domainDirectoryPath) ? getDirectoryLabel(domainDirectoryPath, domain.dirName) : domain.label;
    const fallbackDescription = fs.existsSync(domainDirectoryPath) ? getDirectoryDescription(domainDirectoryPath) : '';
    const fallbackPosition = fs.existsSync(domainDirectoryPath) ? getDirectoryPosition(domainDirectoryPath) : domain.position;
    return {
      ...domain,
      label: domain.label || fallbackLabel,
      description: domain.description || fallbackDescription || undefined,
      position: Number.isFinite(domain.position) ? domain.position : fallbackPosition,
      docId: domain.docId && findDocPathFromDocId(domain.docId) ? domain.docId : undefined,
    };
  });

  return {
    domains: enrichedDomains,
    generalDocs: null,
  };
}

export function buildDocsSidebarsConfig(): SidebarsConfig {
  const catalog = getDocsDomainCatalog();
  const sidebars: SidebarsConfig = {};

  for (const domain of catalog.domains) {
    const items: SidebarItem[] = [];
    for (const docId of domain.ownedDocs) {
      items.push(docId);
    }
    for (const root of domain.ownedRoots) {
      const fullRootPath = path.join(DOCS_ROOT, root);
      if (fs.existsSync(fullRootPath) && fs.statSync(fullRootPath).isDirectory() && directoryHasDocsContent(fullRootPath)) {
        if (normalizeToken(root).toLowerCase() === normalizeToken(domain.dirName).toLowerCase()) {
          const landingDocId = getDirectoryLandingDocId(fullRootPath);
          if (landingDocId && domain.showLandingInSidebar === true) {
            items.push(landingDocId);
          }
          items.push(...buildDirectoryChildSidebarItems(fullRootPath));
          continue;
        }

        const categoryItem: SidebarCategoryItem = {
          type: 'category',
          label: getDirectoryLabel(fullRootPath, root),
          items: buildDirectoryChildSidebarItems(fullRootPath),
        };
        const landingDocId = getDirectoryLandingDocId(fullRootPath);
        if (landingDocId) {
          categoryItem.link = {
            type: 'doc',
            id: landingDocId,
          };
        }
        items.push(categoryItem);
      }
    }
    if (items.length === 0 && domain.docId) {
      items.push(domain.docId);
    }
    sidebars[domain.sidebarId] = items;
  }

  if (Object.keys(sidebars).length === 0) {
    sidebars.docsSidebar = [
      {
        type: 'autogenerated',
        dirName: '.',
      },
    ];
  }

  return sidebars;
}
