import type {ReactNode} from 'react';
import Link from '@docusaurus/Link';
import useBaseUrl from '@docusaurus/useBaseUrl';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import Layout from '@theme/Layout';
import Heading from '@theme/Heading';

import styles from './index.module.css';

type SuiteBrandingFields = {
  suiteProjectName?: string;
  suiteDocsTitle?: string;
  suiteTagline?: string;
};

type NavbarLogoConfig = {
  src?: string;
  alt?: string;
};

const domainCards = [
  {
    title: 'Workflow & Standards',
    body: 'Shared setup, workflow, testing, coding standards, and docs guidance.',
    to: '/docs/workflow-standards',
    badge: 'Shared',
  },
  {
    title: 'Project Docs',
    body: 'Game-specific specs, design notes, implementation details, and team runbooks.',
    to: '/docs/project-docs',
    badge: 'Project',
  },
];

const quickLinks = [
  {
    title: 'Open Docs Home',
    body: 'Go straight to the doc surface with the active sidebar, TOC, and edit controls.',
    to: '/docs/',
  },
  {
    title: 'Site Settings',
    body: 'Open theme, branding, domain, and managed override controls from the docs surface.',
    to: '/docs/?siteAdmin=1',
  },
];

export default function Home(): ReactNode {
  const {siteConfig} = useDocusaurusContext();
  const customFields = (siteConfig.customFields ?? {}) as SuiteBrandingFields;
  const projectName = customFields.suiteProjectName?.trim() || 'UE Project';
  const docsTitle = customFields.suiteDocsTitle?.trim() || `${projectName} Docs`;
  const siteTagline =
    customFields.suiteTagline?.trim() ||
    'Repo tooling, Unreal workflow, and living project documentation.';

  const navbarLogo = (((siteConfig.themeConfig as {navbar?: {logo?: NavbarLogoConfig}} | undefined)?.navbar)?.logo);
  const logoSrc = useBaseUrl(navbarLogo?.src ?? '/img/logo.svg');
  const logoAlt = navbarLogo?.alt ?? `${docsTitle} logo`;

  return (
    <Layout title={docsTitle} description={siteTagline}>
      <header className={styles.hero}>
        <div className={styles.heroBackdrop} />
        <div className={styles.heroGrid}>
          <div className={styles.heroCopy}>
            <div className={styles.brandLockup}>
              <img className={styles.brandMark} src={logoSrc} alt={logoAlt} />
              <p className={styles.eyebrow}>Project documentation hub</p>
            </div>
            <Heading as="h1" className={styles.title}>
              {docsTitle}
            </Heading>
            <p className={styles.subtitle}>{siteTagline}</p>
            <div className={styles.actions}>
              <Link className="button button--primary button--lg" to="/docs/">
                Open Docs
              </Link>
              <Link className={styles.ghostButton} to="/docs/?siteAdmin=1">
                Site Settings
              </Link>
            </div>
          </div>
          <aside className={styles.heroPanel}>
            <p className={styles.panelEyebrow}>How the suite is structured</p>
            <Heading as="h2">Two default domains. One managed shell.</Heading>
            <p>
              Shared standards stay separate from project docs, while Docusaurus categories and autogenerated sidebars
              keep the navigation coherent.
            </p>
          </aside>
        </div>
      </header>
      <main>
        <section className={styles.section}>
          <div className={styles.sectionHeader}>
            <p className={styles.sectionLabel}>Domains</p>
            <Heading as="h2">Start from the right container.</Heading>
            <p>Each domain gets its own landing page and its own pages sidebar.</p>
          </div>
          <div className={styles.cardGrid}>
            {domainCards.map((item) => (
              <Link key={item.title} className={styles.card} to={item.to}>
                <span className={styles.cardBadge}>{item.badge}</span>
                <Heading as="h3">{item.title}</Heading>
                <p>{item.body}</p>
                <span className={styles.cardLink}>Open domain</span>
              </Link>
            ))}
          </div>
        </section>

        <section className={styles.section}>
          <div className={styles.sectionHeader}>
            <p className={styles.sectionLabel}>Administration</p>
            <Heading as="h2">Manage the site without rerunning the installer.</Heading>
          </div>
          <div className={styles.grid}>
            {quickLinks.map((item) => (
              <Link key={item.title} className={styles.primaryCard} to={item.to}>
                <Heading as="h3">{item.title}</Heading>
                <p>{item.body}</p>
                <span>Open</span>
              </Link>
            ))}
          </div>
        </section>
      </main>
    </Layout>
  );
}
